# Special unstaked class for all nodes visible in gossip but without stake
unstaked_class:
  name: solana_unstaked
  fwmark: 1

# Different staked classes, the highest matching class will apply
staked_classes:
  - name: solana_staked
    stake_percentage: 0
    fwmark: 9
  - name: solana_high_staked 
    stake_percentage: 0.01
    fwmark: 3
